# Site settings
title: Lycanthropy Studios
email: lycanthropystudio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Specialized 3D studio on render development, video game design, 3D animation and video editing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
